#!/bin/bash

exec 1>&2

ROOT_PATH=$(git rev-parse --show-toplevel)
CHANGED_FILES=$(git diff --cached --name-status | awk '$1 != "D" { print $2 }')
CS=""
PASS=true

# PHP VALIDATION - START
for FILE in $CHANGED_FILES ; do
    if [[ $FILE =~ ^(src|api/src).+\.(php|twig|yaml)$ ]]; then
        CHANGE=$(php-cs-fixer fix $ROOT_PATH/$FILE --rules=@PSR2 --dry-run --using-cache=no 2> /dev/null | sed '$ d' | cut -d ')' -f 2)
        if [ ! -z "$CHANGE" ] ; then
            CS="$CS\n    $FILE"
            git reset $FILE &> /dev/null
        fi
    fi
done

if [ ! -z "$CS" ] ; then
    echo -e "The following files do not conform with FIG PSR-2:
$CS

Fix them in order to commit."
    for FILE in $CS ; do
        git reset $FILE
    done
fi

if [ ! -z "$CS" ] ; then
    echo -e "You can fix it with: php-cs-fixer fix FILE --rules=@PSR2 --using-cache=no"
fi

# PHP VALIDATION - END