clubs:
  type: rest
  resource: App\Controller\ClubController

players:
  type: rest
  resource: App\Controller\PlayerController

coaches:
  type: rest
  resource: App\Controller\CoachController

assets:
  type: rest
  resource: App\Controller\AssetController